### PR TITLE
Add flysystem 2 support

### PR DESCRIPTION
**Pull request by VincentLanglet**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #113
| License       | MIT

I didn't see any impact from the upgrade guide @GregoireHebert

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@vincentchalamon I don't understand the test failure, I'm not sure it's related to my pr

**Comment by vincentchalamon** [comment]
@VincentLanglet It's not part of your PR. The tests ran in the CI require a secret that is not shared (actually) from forks. The owner of this repo (@GregoireHebert) is aware of it and will fix it as soon as he can :-)

**Comment by VincentLanglet** [comment]
> @VincentLanglet It's not part of your PR. The tests ran in the CI require a secret that is not shared (actually) from forks. The owner of this repo (@GregoireHebert) is aware of it and will fix it as soon as he can :-)

Thanks for the quick answer
We'll follow this pr with interest since we currently cannot install the library because of this conflict :)

**Review by dennispansegrau — CHANGES_REQUESTED** [review]
Can you also change the version from ^1.0.8 to ^1.1 please. The other versions have a security advisory. See https://github.com/thephpleague/flysystem/security/advisories/GHSA-9f46-5r25-5wfm for more information.

**Comment by VincentLanglet** [comment]
> Can you also change the version from ^1.0.8 to ^1.1 please. The other versions have a security advisory. See [GHSA-9f46-5r25-5wfm](https://github.com/thephpleague/flysystem/security/advisories/GHSA-9f46-5r25-5wfm) for more information.

`^1.0.8` doesn't forbid you to install the `1.1.14` version

**Comment by VincentLanglet** [comment]
> @VincentLanglet It's not part of your PR. The tests ran in the CI require a secret that is not shared (actually) from forks. The owner of this repo (@GregoireHebert) is aware of it and will fix it as soon as he can :-)

As a quick fix, @vincentchalamon Could you open the same PR directly on the repository in order to have the test running and see if the version 2 is 100% compatible ?

**Comment by vincentchalamon** [comment]
Backported to https://github.com/GregoireHebert/docusign-bundle/pull/115

**Pull request closed without merging**
